set(TOUCHGFX_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/ApplicationFontProvider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/CachedFont.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/CompressedFontCache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/CompressedUnmappedFontCache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/FontCache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Italic_18_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Italic_18_2bpp_4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Italic_20_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_LightItalic_18_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Light_60_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Medium_10_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Medium_18_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Medium_50_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Regular_18_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_18_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_18_2bpp_4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_20_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_25_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_30_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_35_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_40_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_60_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/GeneratedFont.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Italic_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Italic_20_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_LightItalic_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Light_60_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Medium_10_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Medium_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Medium_50_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Regular_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_20_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_25_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_30_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_35_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_40_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_60_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Italic_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Italic_20_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_LightItalic_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Light_60_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Medium_10_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Medium_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Medium_50_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Regular_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_20_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_25_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_30_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_35_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_40_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_60_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/UnmappedDataFont.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/VectorFontRendererBuffers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/common/FrontendApplicationBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/BatteryBigBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/ButtonsBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/HrBarBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/MenuBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/MenuItemNotSelectedBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/MenuItemSelectedBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/SideBarBigBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/SideBarSmallBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TitleBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TitleInfoBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/ToggleBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TrackFace1Base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TrackFace2Base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TrackFace3Base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TrackFace4Base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TrackSummaryBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TrackSummaryHRBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/entermenu_screen/EnterMenuViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/menualerts_screen/MenuAlertsViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/menudistance_screen/MenuDistanceViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/menudistancesaved_screen/MenuDistanceSavedViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/menusettings_screen/MenuSettingsViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/menusteps_screen/MenuStepsViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/menustepssaved_screen/MenuStepsSavedViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/menutime_screen/MenuTimeViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/menutimesaved_screen/MenuTimeSavedViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/track_screen/TrackViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/trackaction_screen/TrackActionViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/trackdiscardconfirmation_screen/TrackDiscardConfirmationViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/trackdiscarded_screen/TrackDiscardedViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/tracklap_screen/TrackLapViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/tracksaved_screen/TrackSavedViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/trackstartconfirmation_screen/TrackStartConfirmationViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/tracksummary_screen/TrackSummaryViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/BitmapDatabase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/SVGDatabase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Background_Gray.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Background_Teal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Background_TealDark.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_BatteryBig_gray1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_BatteryBig_gray2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_BatteryBig_gray3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_BatteryBig_green1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_BatteryBig_green2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_BatteryBig_green3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_BatteryBig_red1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_L1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_L1A.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_L1R.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_L2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_L2A.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_L2R_.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_R1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_R1A.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_R1R.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_R2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_R2A.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_R2R.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_HR_1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_HR_2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_HR_3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_HR_4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_HR_5.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_HR_group.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Heart.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_MenuAssets_CircleCross.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_MenuAssets_CircleTick.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_MenuAssets_Cross.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_MenuAssets_CrossYellow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_MenuAssets_Tick.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_SideBarBig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_SideBarSmall.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Toggle_Def.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Toggle_Handle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Toggle_Off.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Toggle_On.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/texts/src/LanguageGb.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/texts/src/Texts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/texts/src/TypedTextDatabase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/common/FrontendApplication.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/BatteryBig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/Buttons.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/HrBar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/Menu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/MenuItemNotSelected.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/MenuItemSelected.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/PolyLine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/SideBarBig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/SideBarSmall.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/Title.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/TitleInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/Toggle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/TrackFace1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/TrackFace2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/TrackFace3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/TrackFace4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/TrackSummary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/TrackSummaryHR.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/entermenu_screen/EnterMenuPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/entermenu_screen/EnterMenuView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menualerts_screen/MenuAlertsPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menualerts_screen/MenuAlertsView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menudistance_screen/MenuDistancePresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menudistance_screen/MenuDistanceView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menudistancesaved_screen/MenuDistanceSavedPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menudistancesaved_screen/MenuDistanceSavedView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menusettings_screen/MenuSettingsPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menusettings_screen/MenuSettingsView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menusteps_screen/MenuStepsPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menusteps_screen/MenuStepsView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menustepssaved_screen/MenuStepsSavedPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menustepssaved_screen/MenuStepsSavedView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menutime_screen/MenuTimePresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menutime_screen/MenuTimeView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menutimesaved_screen/MenuTimeSavedPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/menutimesaved_screen/MenuTimeSavedView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/model/Model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/track_screen/TrackPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/track_screen/TrackView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/trackaction_screen/TrackActionPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/trackaction_screen/TrackActionView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/trackdiscardconfirmation_screen/TrackDiscardConfirmationPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/trackdiscardconfirmation_screen/TrackDiscardConfirmationView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/trackdiscarded_screen/TrackDiscardedPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/trackdiscarded_screen/TrackDiscardedView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/tracklap_screen/TrackLapPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/tracklap_screen/TrackLapView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/tracksaved_screen/TrackSavedPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/tracksaved_screen/TrackSavedView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/trackstartconfirmation_screen/TrackStartConfirmationPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/trackstartconfirmation_screen/TrackStartConfirmationView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/tracksummary_screen/TrackSummaryPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/tracksummary_screen/TrackSummaryView.cpp
)

set(TOUCHGFX_INCLUDE_DIRS
    ${CMAKE_CURRENT_LIST_DIR}/touchgfx/framework/include
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/include
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/include
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/include
    ${CMAKE_CURRENT_LIST_DIR}/generated/texts/include
    ${CMAKE_CURRENT_LIST_DIR}/generated/videos/include
    ${CMAKE_CURRENT_LIST_DIR}/gui/include
)

set(TOUCHGFX_LIBS
    ${CMAKE_CURRENT_LIST_DIR}/touchgfx/lib/core/cortex_m33/gcc/libtouchgfx-float-abi-hard.a
)