set(TOUCHGFX_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/ApplicationFontProvider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/CachedFont.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/CompressedFontCache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/CompressedUnmappedFontCache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/FontCache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Italic_18_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Italic_18_2bpp_4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Italic_20_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Light_60_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_LightItalic_18_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Medium_10_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Medium_18_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Medium_50_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_Regular_18_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_18_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_18_2bpp_4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_20_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_25_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_30_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_35_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_40_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Font_Poppins_SemiBold_60_2bpp_0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/GeneratedFont.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Italic_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Italic_20_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Light_60_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_LightItalic_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Medium_10_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Medium_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Medium_50_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_Regular_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_20_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_25_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_30_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_35_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_40_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Kerning_Poppins_SemiBold_60_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Italic_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Italic_20_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Light_60_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_LightItalic_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Medium_10_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Medium_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Medium_50_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_Regular_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_18_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_20_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_25_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_30_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_35_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_40_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/Table_Poppins_SemiBold_60_2bpp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/UnmappedDataFont.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/src/VectorFontRendererBuffers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/action_screen/ActionViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/alarm_screen/AlarmViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/common/FrontendApplicationBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/ButtonsBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/MenuWheelBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/MenuWheelItemNotSelectedBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/MenuWheelItemSelectedBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TimeWheelBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TimeWheelItemHoursNotSelectedBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TimeWheelItemHoursSelectedBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TimeWheelItemMinutesNotSelectedBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TimeWheelItemMinutesSelectedBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/TitleBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/containers/ToggleBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/deleted_screen/DeletedViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/main_screen/MainViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/saved_screen/SavedViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/settime_screen/SetTimeViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/src/start_screen/StartViewBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/BitmapDatabase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_AlarmBig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_L1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_L1A.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_L1R.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_L2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_L2A.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_L2R_.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_R1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_R1A.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_R1R.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_R2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_R2A.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Button_R2R.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_MenuAssets_CircleCross.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_MenuAssets_CirclePlus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_MenuAssets_CircleTick.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_MenuAssets_Tick.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Toggle_Def.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Toggle_Handle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Toggle_Off.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/image_Toggle_On.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/src/SVGDatabase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/texts/src/LanguageGb.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/texts/src/Texts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/texts/src/TypedTextDatabase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/action_screen/ActionPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/action_screen/ActionView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/alarm_screen/AlarmPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/alarm_screen/AlarmView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/common/FrontendApplication.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/Buttons.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/MenuWheel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/MenuWheelItemNotSelected.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/MenuWheelItemSelected.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/TimeWheel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/TimeWheelItemHoursNotSelected.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/TimeWheelItemHoursSelected.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/TimeWheelItemMinutesNotSelected.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/TimeWheelItemMinutesSelected.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/Title.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/containers/Toggle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/deleted_screen/DeletedPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/deleted_screen/DeletedView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/main_screen/MainPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/main_screen/MainView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/model/Model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/saved_screen/SavedPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/saved_screen/SavedView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/settime_screen/SetTimePresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/settime_screen/SetTimeView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/start_screen/StartPresenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gui/src/start_screen/StartView.cpp
)

set(TOUCHGFX_INCLUDE_DIRS
    ${CMAKE_CURRENT_LIST_DIR}/touchgfx/framework/include
    ${CMAKE_CURRENT_LIST_DIR}/generated/fonts/include
    ${CMAKE_CURRENT_LIST_DIR}/generated/gui_generated/include
    ${CMAKE_CURRENT_LIST_DIR}/generated/images/include
    ${CMAKE_CURRENT_LIST_DIR}/generated/texts/include
    ${CMAKE_CURRENT_LIST_DIR}/generated/videos/include
    ${CMAKE_CURRENT_LIST_DIR}/gui/include
)

set(TOUCHGFX_LIBS
    ${CMAKE_CURRENT_LIST_DIR}/touchgfx/lib/core/cortex_m33/gcc/libtouchgfx-float-abi-hard.a
)